name: Helm Charts
on:
  push:
    branches:
      - github-actions

  pull_request:
      types: [opened, reopened, synchronize]
      paths:
          - "charts/**"

jobs:
  test:
    name: Test Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        id: chart-install
        run: ct install --remote origin --all
        if: steps.list-changed.outputs.changed == 'true'

#  release:
#    if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main'
#    name: Publish Helm Chart
#    runs-on: ubuntu-latest
#    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
#    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
#    permissions:
#      contents: write
#    steps:
#      - name: Configure Git
#        run: |
#          git config user.name "$GITHUB_ACTOR"
#          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#
#      - name: Run chart-releaser
#        uses: helm/chart-releaser-action@v1.5.0
#        env:
#          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
